"""
radar/models/radar_metrics_snapshot.py — Bloco 26 V2: Metrics Snapshot (v2)

RadarMetricsSnapshot stores computed scores from StrategicOpportunityEngine
plus the Validation Strategy generated in Phase 6.

Constitutional constraints:
  - Scores come EXCLUSIVELY from StrategicOpportunityEngine — NEVER recomputed here
  - validation_strategy is advisory text derived from Core outputs — no math
  - Append-only (never mutated after creation)
  - Schema version 2 adds: cluster_id, validation_strategy embed
"""
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional


# Valid ICE values as emitted by Core (V2: ALTO / MODERADO / BLOQUEADO)
_VALID_ICE = {"ALTO", "MODERADO", "BLOQUEADO"}


@dataclass(frozen=True)
class RadarMetricsSnapshot:
    """
    Lightweight scoring + strategy audit record from a completed V2 evaluation.

    All score fields are READ-ONLY copies from StrategicOpportunityEngine output.
    validation_strategy is an advisory dict generated by validation_strategy.py (Phase 6).

    Fields (required):
        evaluation_event_id : event_id from StrategicOpportunityEngine output
        snapshot_event_id   : event_id of the RadarDatasetSnapshot evaluated
        cluster_id          : dominant cluster identifier (from Phase 4)
        keyword             : The keyword evaluated
        emotional           : Emotional Score (0–100) — from Core, never recomputed
        monetization        : Monetization Score (0–100) — from Core, never recomputed
        growth_score        : Growth Score (0–100) — from Core, never recomputed
        growth_percent      : Growth % — raw input from provider
        score_final         : Final weighted score — from Core (post-penalty)
        cluster_ratio       : Cluster ratio — from Phase 4 / Core
        cluster_penalty     : Whether cluster penalty was applied — from Core
        ice                 : ICE classification ("ALTO" | "MODERADO" | "BLOQUEADO")
        recommended         : Whether expansion was recommended — from Core
        status              : Result status string
        noise_score         : Noise filter score at evaluation time
        global_state        : System global state at evaluation time

    Fields (optional):
        validation_strategy : Advisory strategy dict from Phase 6 (None if ICE=BLOQUEADO)

    Auto-generated:
        event_id            : Unique metrics record identifier (uuid4)
        timestamp           : UTC creation timestamp (ISO)
        version             : Schema version = "2"
    """
    # --- Mandatory identification ---
    evaluation_event_id: str
    snapshot_event_id:   str
    cluster_id:          str
    keyword:             str

    # --- Core scores (read-only copies, never recomputed) ---
    emotional:       float
    monetization:    float
    growth_score:    float
    growth_percent:  float
    score_final:     float
    cluster_ratio:   float
    cluster_penalty: bool
    ice:             str
    recommended:     bool
    status:          str
    noise_score:     float
    global_state:    str

    # --- Phase 6: advisory strategy (None when ICE=BLOQUEADO) ---
    validation_strategy: Optional[dict] = field(default=None)

    # --- Auto-generated ---
    event_id:  str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    version:   str = "2"

    def __post_init__(self) -> None:
        # Validate score ranges
        for name, val in [
            ("emotional",    self.emotional),
            ("monetization", self.monetization),
            ("growth_score", self.growth_score),
            ("noise_score",  self.noise_score),
        ]:
            if not (0.0 <= float(val) <= 100.0):
                raise ValueError(f"RadarMetricsSnapshot.{name}={val} must be in [0, 100]")

        # ICE must be one of three valid constitutional values
        if self.ice not in _VALID_ICE:
            raise ValueError(
                f"RadarMetricsSnapshot.ice='{self.ice}' is invalid. "
                f"Must be one of {sorted(_VALID_ICE)}"
            )

        # validation_strategy only allowed for non-BLOQUEADO cycles
        if self.ice == "BLOQUEADO" and self.validation_strategy is not None:
            raise ValueError(
                "RadarMetricsSnapshot: validation_strategy must be None when ice='BLOQUEADO'. "
                "Strategy is not generated for blocked cycles."
            )

    def to_dict(self) -> dict:
        """
        Serialize to a flat dict for append-only JSONL persistence.

        Constitutional guarantee: returns the same values that were provided at
        construction — no recalculation of any score field.
        """
        d = {
            # Identification
            "event_id":            self.event_id,
            "timestamp":           self.timestamp,
            "version":             self.version,
            "evaluation_event_id": self.evaluation_event_id,
            "snapshot_event_id":   self.snapshot_event_id,
            "cluster_id":          self.cluster_id,
            "keyword":             self.keyword,
            # Core scores (verbatim from StrategicOpportunityEngine)
            "emotional":           self.emotional,
            "monetization":        self.monetization,
            "growth_score":        self.growth_score,
            "growth_percent":      self.growth_percent,
            "score_final":         self.score_final,
            "cluster_ratio":       self.cluster_ratio,
            "cluster_penalty":     self.cluster_penalty,
            "ice":                 self.ice,
            "recommended":         self.recommended,
            "status":              self.status,
            "noise_score":         self.noise_score,
            "global_state":        self.global_state,
        }
        if self.validation_strategy is not None:
            d["validation_strategy"] = self.validation_strategy
        return d

    @classmethod
    def from_engine_result(
        cls,
        engine_result:       dict,
        snapshot_event_id:   str,
        noise_score:         float,
        cluster_id:          str = "",
        validation_strategy: Optional[dict] = None,
    ) -> "RadarMetricsSnapshot":
        """
        Factory: construct from StrategicOpportunityEngine.evaluate_opportunity_v2() output.

        Args:
            engine_result:       Dict from Core (carries all score fields)
            snapshot_event_id:   event_id of the RadarDatasetSnapshot
            noise_score:         Noise_Filter_Score at evaluation time
            cluster_id:          Dominant cluster identifier (from Phase 4)
            validation_strategy: Advisory strategy dict from Phase 6, or None

        Constitutional guarantee: copies values verbatim — no arithmetic performed.
        """
        status = engine_result.get("status", "qualified") if "status" in engine_result else "qualified"
        ice = engine_result.get("ice", "BLOQUEADO")
        # Normalise legacy "MEDIO" → "MODERADO"
        if ice == "MEDIO":
            ice = "MODERADO"
        # Ensure validation_strategy is None for BLOQUEADO
        strat = validation_strategy if ice != "BLOQUEADO" else None

        return cls(
            evaluation_event_id = engine_result.get("event_id", ""),
            snapshot_event_id   = snapshot_event_id,
            cluster_id          = cluster_id,
            keyword             = engine_result.get("product_id", ""),
            emotional           = float(engine_result.get("emotional",    0.0)),
            monetization        = float(engine_result.get("monetization", 0.0)),
            growth_score        = float(engine_result.get("growth_score", 0.0)),
            growth_percent      = float(engine_result.get("growth_percent", 0.0)),
            score_final         = float(engine_result.get("score_final",  0.0)),
            cluster_ratio       = float(engine_result.get("cluster_ratio", 0.0)),
            cluster_penalty     = bool(engine_result.get("cluster_penalty", False)),
            ice                 = ice,
            recommended         = bool(engine_result.get("recommended", False)),
            status              = status,
            noise_score         = float(noise_score),
            global_state        = engine_result.get("global_state", "UNKNOWN"),
            validation_strategy = strat,
        )
